# before_script: chmod 0777 ./node_modules/.bin/mocha

language: node_js
node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info |
node_modules/coveralls/bin/coveralls.js"
